import "@radix-ui/themes/styles.css";
import "@/styles/globals.css";

import { Analytics } from "@vercel/analytics/next";
import {
  Cinzel_Decorative,
  Cormorant_Garamond,
  Crimson_Pro,
} from "next/font/google";
import { type Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { MotionProvider } from "@/components/motion-provider";
import { SkipToContent } from "@/components/skip-to-content";
import {
  StructuredData,
  createWebSiteSchema,
} from "@/components/structured-data";

const BASE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://sacredgeometry.site";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "Sacred Geometry - Explore Divine Patterns and Platonic Solids",
    template: "%s | Sacred Geometry",
  },
  description:
    "Discover the mathematical principles and divine patterns underlying the universe. Explore Platonic solids, the Flower of Life, Metatron's Cube, and other sacred geometric forms.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  openGraph: {
    type: "website",
    locale: "en_US",
    siteName: "Sacred Geometry",
    // OG image is dynamically generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
  },
};

// Display font for hero titles and page headings
const cinzelDecorative = Cinzel_Decorative({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-display",
  display: "swap",
});

// Heading font for section headings and card titles
const cormorantGaramond = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["500", "600"],
  variable: "--font-heading",
  display: "swap",
});

// Body font for text and descriptions
const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-body",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${cinzelDecorative.variable} ${cormorantGaramond.variable} ${crimsonPro.variable}`}
    >
      <body>
        <StructuredData
          data={createWebSiteSchema(
            BASE_URL,
            "Sacred Geometry",
            "Discover the mathematical principles and divine patterns underlying the universe. Explore Platonic solids, the Flower of Life, Metatron's Cube, and other sacred geometric forms."
          )}
        />
        <SkipToContent />
        <Theme appearance="dark">
          <MotionProvider>
            <Header />
            <main id="main-content">{children}</main>
            <Footer />
          </MotionProvider>
        </Theme>
      </body>
      <Analytics />
    </html>
  );
}
